# Generated by Django 5.1.4 on 2025-02-06 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course_app', '0011_alter_course_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='course_description',
            field=models.TextField(default='No description available'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='course_name',
            field=models.CharField(default='No course name provided', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='course_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='description_keywords',
            field=models.TextField(default='No keywords provided'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='difficulty_level',
            field=models.CharField(default='Medium', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_id',
            field=models.CharField(max_length=50),
        ),
    ]
